import CoolProp.CoolProp as CP

def calculate_turbine_power(mass_flow_rate, P_in, T_in, P_out, efficiency):
    """
    Calculates the power output of a steam turbine.
    
    Args:
        mass_flow_rate (float): Mass flow rate in kg/s
        P_in (float): Inlet pressure in Pascals (Pa)
        T_in (float): Inlet temperature in Kelvin (K)
        P_out (float): Outlet pressure in Pascals (Pa)
        efficiency (float): Isentropic efficiency (0.0 to 1.0)
        
    Returns:
        dict: Dictionary containing power output and state properties
    """
    fluid = 'Water'

    # 1. Get Inlet State Properties (Enthalpy and Entropy)
    # We use Pressure (P) and Temperature (T) as inputs
    h_in = CP.PropsSI('H', 'P', P_in, 'T', T_in, fluid)
    s_in = CP.PropsSI('S', 'P', P_in, 'T', T_in, fluid)

    # 2. Calculate Isentropic Outlet State (Ideal Case)
    # For an ideal turbine, entropy remains constant (s_out_ideal = s_in)
    # We use Pressure (P) and Entropy (S) to find the ideal outlet enthalpy
    h_out_ideal = CP.PropsSI('H', 'P', P_out, 'S', s_in, fluid)

    # 3. Calculate Actual Outlet Enthalpy
    # Actual work = Efficiency * Ideal work
    # (h_in - h_out_actual) = efficiency * (h_in - h_out_ideal)
    delta_h_ideal = h_in - h_out_ideal
    delta_h_actual = delta_h_ideal * efficiency
    
    h_out_actual = h_in - delta_h_actual

    # 4. Calculate Power Output
    # Power (Watts) = Mass Flow Rate (kg/s) * Enthalpy Drop (J/kg)
    power_watts = mass_flow_rate * delta_h_actual
    
    # Optional: Get actual outlet temperature for reporting
    T_out_actual = CP.PropsSI('T', 'P', P_out, 'H', h_out_actual, fluid)

    return {
        "power_output_mw": power_watts / 1e6, # Convert to Megawatts
        "enthalpy_in_kj": h_in / 1000,
        "enthalpy_out_actual_kj": h_out_actual / 1000,
        "temperature_out_celsius": T_out_actual - 273.15
    }

# # --- Simulation Parameters ---
# target_power_mw = 50.0  # Let's say we WANT 50 MW
# engine_efficiency = 0.85 # 85% isentropic efficiency

# # Inlet: 100 Bar (10 MPa), 500 Celsius
# P_inlet = 100 * 1e5 
# T_inlet = 500 + 273.15 

# # Outlet: 0.1 Bar (10 kPa) - typical condenser pressure
# P_outlet = 0.1 * 1e5

# # --- The "Solver" Part ---
# # In a real system, you'd use an optimization loop here. 
# # For this simple linear case, we can just calculate the required mass flow directly.
# # But let's simulate a "guess" first to show how CoolProp is used.

# # Let's guess 1 kg/s flow
# test_run = calculate_turbine_power(1.0, P_inlet, T_inlet, P_outlet, engine_efficiency)
# power_per_kg = test_run['power_output_mw']

# print(f"--- Single Unit Simulation ---")
# print(f"Input Steam: 100 Bar, 500°C")
# print(f"Turbine Efficiency: {engine_efficiency*100}%")
# print(f"Power generated by 1 kg/s: {power_per_kg:.4f} MW")

# # Now, calculate the required input to hit the target
# required_mass_flow = target_power_mw / power_per_kg

# print(f"\n--- Solver Result ---")
# print(f"Target Power: {target_power_mw} MW")
# print(f"Required Mass Flow Rate: {required_mass_flow:.2f} kg/s")

# # Verify
# final_run = calculate_turbine_power(required_mass_flow, P_inlet, T_inlet, P_outlet, engine_efficiency)
# print(f"Verification Calculation: {final_run['power_output_mw']:.2f} MW")
# print(f"Steam Exit Temperature: {final_run['temperature_out_celsius']:.2f} °C")